class UIKeys:
    """Keys for UI widgets in ``st.session_state``."""

    PROFILE_TEXT_INPUT = "ui.profile_text_input"
    PROFILE_FILE_UPLOADER = "ui.profile_file_uploader"
    PROFILE_URL_INPUT = "ui.profile_url_input"
    LANG_SELECT = "ui.lang_select"
    INPUT_METHOD = "ui.input_method"
    COMPANY_LOGO = "ui.company_logo"
    MODEL_SELECT = "ui.model_select"
    VERBOSITY_SELECT = "ui.verbosity_select"
    REASONING_SELECT = "ui.reasoning_select"
    SALARY_ESTIMATE = "ui.salary.estimate"
    SALARY_REFRESH = "ui.salary.refresh"
    SALARY_EXPLANATION = "ui.salary.explanation"
    SALARY_EXPLANATION_BUTTON = "ui.salary.explanation_button"
    TONE_SELECT = "ui.summary.tone"
    NUM_QUESTIONS = "ui.summary.num_questions"
    AUDIENCE_SELECT = "ui.summary.audience"
    JOB_AD_OUTPUT = "ui.summary.job_ad_output"
    INTERVIEW_OUTPUT = "ui.summary.interview_output"
    JOB_AD_FIELD_PREFIX = "ui.job_ad.field."
    JOB_AD_STEP_SELECT = "ui.job_ad.step_select"
    JOB_AD_STEP_FIELD_PREFIX = "ui.job_ad.step_field."
    JOB_AD_FIELD_OVERVIEW = "ui.job_ad.overview"
    JOB_AD_TARGET_SELECT = "ui.job_ad.target"
    JOB_AD_CUSTOM_TARGET = "ui.job_ad.custom_target"
    JOB_AD_MANUAL_TITLE = "ui.job_ad.manual_title"
    JOB_AD_MANUAL_TEXT = "ui.job_ad.manual_text"
    JOB_AD_FEEDBACK = "ui.job_ad.feedback"
    REFINE_JOB_AD = "ui.job_ad.refine"
    REQUIREMENTS_OCC_SEARCH = "ui.requirements.occupation_search"
    REQUIREMENTS_OCC_SELECT = "ui.requirements.occupation_select"
    REQUIREMENTS_SHOW_ALL_ESCO = "ui.requirements.show_all_esco"
    REQUIREMENTS_ESCO_SKILL_SELECT = "ui.requirements.esco_skill_select"
    REQUIREMENTS_FETCH_AI_SUGGESTIONS = "ui.requirements.fetch_ai_suggestions"
    REQUIREMENTS_FETCH_ESCO_SUGGESTIONS = "ui.requirements.fetch_esco_suggestions"
    RESPONSIBILITY_SUGGEST = "ui.requirements.responsibilities.suggest"
    POSITION_ESCO_OCCUPATION = "ui.position.esco_occupation"
    JOB_AD_FONT = "ui.job_ad.font"
    JOB_AD_FORMAT = "ui.job_ad.format"
    JOB_AD_LOGO_UPLOAD = "ui.job_ad.logo_upload"
    INTERVIEW_FORMAT = "ui.summary.interview_format"
    SUMMARY_SELECTED_GROUP = "ui.summary.selected_group"
    COMPANY_HQ_LOCATION = "ui.company.hq_location"
    COMPANY_BRANDING_UPLOAD = "ui.company.branding_upload"
    COMPANY_BRAND_KEYWORDS = "ui.summary.company.brand_keywords"
    JOB_AD_BRAND_TONE = "ui.summary.job_ad.brand_keywords"
    JOB_AD_BRAND_TONE_INPUT = "ui.summary.job_ad.brand_keywords.input"
    JOB_AD_BRAND_TONE_SYNC_FLAG = "ui.summary.job_ad.brand_keywords.sync"


class StateKeys:
    """Keys for data stored in ``st.session_state``."""

    PROFILE = "profile_data"
    RAW_TEXT = "profile_raw_text"
    RAW_BLOCKS = "profile_raw_blocks"
    STEP = "current_step"
    SCROLL_TO_TOP = "ui.scroll_to_top"
    FOLLOWUPS = "followup_questions"
    FOLLOWUPS_RESPONSE_ID = "followups.response_id"
    RAG_CONTEXT_SKIPPED = "followups.rag_skipped"
    AUTOFILL_DECISIONS = "autofill_decisions"
    USAGE = "api_usage"
    JOB_AD_MD = "data.job_ad_md"
    BOOLEAN_STR = "data.boolean_str"
    INTERVIEW_GUIDE_MD = "data.interview_md"
    INTERVIEW_GUIDE_DATA = "data.interview_guide"
    SKILL_SUGGESTIONS = "skill_suggestions"
    SKILL_SUGGESTION_HINTS = "skill_suggestion_hints"
    SKILL_BOARD_STATE = "ui.requirements.skill_board"
    SKILL_BOARD_META = "ui.requirements.skill_board_meta"
    REQUIREMENTS_AI_OPT_IN = "requirements.ai_opt_in"
    REQUIREMENTS_ESCO_OPT_IN = "requirements.esco_opt_in"
    BENEFIT_SUGGESTIONS = "benefit_suggestions"
    BENEFIT_SUGGESTION_HINTS = "benefit_suggestion_hints"
    RESPONSIBILITY_SUGGESTIONS = "responsibility_suggestions"
    LOCAL_BENEFIT_SUGGESTIONS = "benefit_suggestions.local"
    LOCAL_BENEFIT_CONTEXT = "benefit_suggestions.local_context"
    ONBOARDING_SUGGESTIONS = "onboarding_suggestions"
    EXTRACTION_SUMMARY = "extraction_summary"
    EXTRACTION_MISSING = "extraction_missing"
    EXTRACTION_RAW_PROFILE = "extraction_raw_profile"
    PROFILE_METADATA = "profile_metadata"
    ESCO_SKILLS = "extraction_esco_skills"
    ESCO_MISSING_SKILLS = "extraction_esco_missing_skills"
    # NOTE: ``ESCO_OCCUPATION_OPTIONS`` was historically reused for both the
    # extraction snapshot and the UI cache.  The names were split in 2024-08 to
    # prevent UI refreshes from wiping extraction results.  Keep the
    # ``EXTRACTION_*`` key for data snapshots and the ``UI_*`` key for the
    # interactive picker cache.
    EXTRACTION_ESCO_OCCUPATION_OPTIONS = "extraction_esco_occupation_options"
    ESCO_SELECTED_OCCUPATIONS = "data.esco_selected_occupations"
    BIAS_FINDINGS = "data.bias_findings"
    SKILL_BUCKETS = "skill_buckets"
    COMPANY_PAGE_SUMMARIES = "company.page_summaries"
    COMPANY_PAGE_BASE = "company.page_base_url"
    COMPANY_PAGE_TEXT_CACHE = "company.page_text_cache"
    COMPANY_BRANDING_ASSET = "company.branding_asset"

    JOB_AD_SELECTED_FIELDS = "data.job_ad.selected_fields"
    JOB_AD_SELECTED_VALUES = "data.job_ad.selected_values"
    JOB_AD_MANUAL_ENTRIES = "data.job_ad.manual_entries"
    JOB_AD_SELECTED_AUDIENCE = "data.job_ad.selected_audience"
    JOB_AD_FONT_CHOICE = "data.job_ad.font"
    JOB_AD_LOGO_DATA = "data.job_ad.logo"
    INTERVIEW_AUDIENCE = "data.interview.audience"
    UI_ESCO_OCCUPATION_OPTIONS = "data.esco_occupation_options"
    # Backwards compatibility for legacy imports; prefer
    # ``UI_ESCO_OCCUPATION_OPTIONS`` going forward.
    ESCO_OCCUPATION_OPTIONS = UI_ESCO_OCCUPATION_OPTIONS
    SUMMARY_FOLLOWUP_SNAPSHOT = "data.summary.followup_snapshot"
    SUMMARY_SELECTED_GROUP = UIKeys.SUMMARY_SELECTED_GROUP
    COMPLETED_SECTIONS = "wizard.completed_sections"
    FIRST_INCOMPLETE_SECTION = "wizard.first_incomplete_section"
    PENDING_INCOMPLETE_JUMP = "wizard.pending_incomplete_jump"
    WIZARD_STEP_COUNT = "wizard.step_count"
    STEPPER_WARNING = "wizard.stepper_warning"
    WIZARD_AUTOFILL_DECISIONS = "wizard.autofill_decisions"
