class UIKeys:
    """Keys for UI widgets in ``st.session_state``."""

    PROFILE_TEXT_INPUT = "ui.profile_text_input"
    PROFILE_FILE_UPLOADER = "ui.profile_file_uploader"
    PROFILE_URL_INPUT = "ui.profile_url_input"
    LANG_SELECT = "ui.lang_select"
    INPUT_METHOD = "ui.input_method"
    COMPANY_LOGO = "ui.company_logo"
    MODEL_SELECT = "ui.model_select"
    REASONING_SELECT = "ui.reasoning_select"
    SALARY_ESTIMATE = "ui.salary.estimate"
    SALARY_REFRESH = "ui.salary.refresh"
    SALARY_EXPLANATION = "ui.salary.explanation"
    SALARY_EXPLANATION_BUTTON = "ui.salary.explanation_button"
    TONE_SELECT = "ui.summary.tone"
    NUM_QUESTIONS = "ui.summary.num_questions"
    AUDIENCE_SELECT = "ui.summary.audience"
    JOB_AD_FEEDBACK = "ui.job_ad.feedback"
    REFINE_JOB_AD = "ui.job_ad.refine"


class StateKeys:
    """Keys for data stored in ``st.session_state``."""

    PROFILE = "profile_data"
    RAW_TEXT = "profile_raw_text"
    STEP = "current_step"
    FOLLOWUPS = "followup_questions"
    USAGE = "api_usage"
    JOB_AD_MD = "data.job_ad_md"
    BOOLEAN_STR = "data.boolean_str"
    INTERVIEW_GUIDE_MD = "data.interview_md"
    SKILL_SUGGESTIONS = "skill_suggestions"
    BENEFIT_SUGGESTIONS = "benefit_suggestions"
    EXTRACTION_SUMMARY = "extraction_summary"
    EXTRACTION_MISSING = "extraction_missing"
    EXTRACTION_RAW_PROFILE = "extraction_raw_profile"
    ESCO_SKILLS = "extraction_esco_skills"
    BIAS_FINDINGS = "data.bias_findings"
    SKILL_BUCKETS = "skill_buckets"
    COMPANY_PAGE_SUMMARIES = "company.page_summaries"
    COMPANY_PAGE_BASE = "company.page_base_url"
