# Streamlit deployment defaults for Cognitive Staffing.
# EN: Pin the Python runtime and install command so Streamlit uses pyproject.toml.
# DE: Fixiert Python-Version und Installationsbefehl, damit Streamlit pyproject.toml verwendet.
[python]
version = "3.11"
installCommand = "pip install ."
