"""Auto-generated RecruitingWizard export helpers.

This file is generated by ``scripts/propagate_schema.py``.
Do not edit manually.
"""

# CS_SCHEMA_PROPAGATE | PIPE_PROP
from __future__ import annotations

from dataclasses import dataclass
from typing import Final, Iterable, Mapping

from core.schema import RecruitingWizard

from .models import RecruitingWizardExport


@dataclass(frozen=True, slots=True)
class WizardExportField:
    """Metadata for a canonical RecruitingWizard export field."""

    path: str
    python_type: str
    is_collection: bool


WIZARD_EXPORT_FIELDS: Final[tuple[WizardExportField, ...]] = (
    WizardExportField(path="benefits.bonus", python_type="str | None", is_collection=False),
    WizardExportField(path="benefits.currency", python_type="str | None", is_collection=False),
    WizardExportField(path="benefits.equity", python_type="str | None", is_collection=False),
    WizardExportField(path="benefits.on_call", python_type="core.schema.OnCallRequirement", is_collection=False),
    WizardExportField(path="benefits.perks", python_type="list[str]", is_collection=True),
    WizardExportField(path="benefits.relocation_support", python_type="str | None", is_collection=False),
    WizardExportField(path="benefits.salary_range", python_type="str | None", is_collection=False),
    WizardExportField(path="benefits.wellbeing", python_type="list[str]", is_collection=True),
    WizardExportField(path="company.benefits", python_type="list[str]", is_collection=True),
    WizardExportField(path="company.brand_color", python_type="str | None", is_collection=False),
    WizardExportField(path="company.brand_keywords", python_type="str | None", is_collection=False),
    WizardExportField(path="company.brand_name", python_type="str | None", is_collection=False),
    WizardExportField(path="company.claim", python_type="str | None", is_collection=False),
    WizardExportField(
        path="company.contact_email", python_type="pydantic.networks.EmailStr | Literal[''] | None", is_collection=False
    ),
    WizardExportField(path="company.contact_name", python_type="str | None", is_collection=False),
    WizardExportField(path="company.contact_phone", python_type="str | None", is_collection=False),
    WizardExportField(path="company.culture", python_type="str | None", is_collection=False),
    WizardExportField(path="company.description", python_type="str | None", is_collection=False),
    WizardExportField(path="company.hq_location", python_type="str | None", is_collection=False),
    WizardExportField(path="company.industries", python_type="list[str]", is_collection=True),
    WizardExportField(path="company.industry", python_type="str | None", is_collection=False),
    WizardExportField(path="company.legal_name", python_type="str | None", is_collection=False),
    WizardExportField(path="company.locations", python_type="list[str]", is_collection=True),
    WizardExportField(path="company.logo_url", python_type="pydantic.networks.HttpUrl | None", is_collection=False),
    WizardExportField(path="company.mission", python_type="str | None", is_collection=False),
    WizardExportField(path="company.name", python_type="str | None", is_collection=False),
    WizardExportField(path="company.size", python_type="str | None", is_collection=False),
    WizardExportField(path="company.tagline", python_type="str | None", is_collection=False),
    WizardExportField(path="company.values", python_type="list[str]", is_collection=True),
    WizardExportField(path="company.website", python_type="str | None", is_collection=False),
    WizardExportField(path="department.function", python_type="str | None", is_collection=False),
    WizardExportField(path="department.leader_name", python_type="str | None", is_collection=False),
    WizardExportField(path="department.leader_title", python_type="str | None", is_collection=False),
    WizardExportField(path="department.name", python_type="str | None", is_collection=False),
    WizardExportField(path="department.strategic_goals", python_type="str | None", is_collection=False),
    WizardExportField(path="interview_process.decision_timeline", python_type="str | None", is_collection=False),
    WizardExportField(path="interview_process.evaluation_criteria", python_type="list[str]", is_collection=True),
    WizardExportField(path="interview_process.interviewers", python_type="list[str]", is_collection=True),
    WizardExportField(path="interview_process.notes", python_type="str | None", is_collection=False),
    WizardExportField(path="interview_process.steps", python_type="list[str]", is_collection=True),
    WizardExportField(
        path="missing_fields.root", python_type="dict[str, core.schema.MissingFieldEntry]", is_collection=False
    ),
    WizardExportField(path="position.customer_contact_details", python_type="str | None", is_collection=False),
    WizardExportField(path="position.customer_contact_required", python_type="bool | None", is_collection=False),
    WizardExportField(path="position.reporting_manager_name", python_type="str | None", is_collection=False),
    WizardExportField(path="position.reports_to", python_type="str | None", is_collection=False),
    WizardExportField(path="position.supervises", python_type="int | None", is_collection=False),
    WizardExportField(path="requirements.background_check_required", python_type="bool | None", is_collection=False),
    WizardExportField(path="requirements.portfolio_required", python_type="bool | None", is_collection=False),
    WizardExportField(path="requirements.reference_check_required", python_type="bool | None", is_collection=False),
    WizardExportField(path="role.employment_type", python_type="core.schema.EmploymentType", is_collection=False),
    WizardExportField(path="role.on_call", python_type="core.schema.OnCallRequirement", is_collection=False),
    WizardExportField(path="role.outcomes", python_type="list[str]", is_collection=True),
    WizardExportField(path="role.purpose", python_type="str | None", is_collection=False),
    WizardExportField(path="role.reports_to", python_type="str | None", is_collection=False),
    WizardExportField(path="role.seniority", python_type="str | None", is_collection=False),
    WizardExportField(path="role.title", python_type="str | None", is_collection=False),
    WizardExportField(path="role.work_location", python_type="str | None", is_collection=False),
    WizardExportField(path="role.work_model", python_type="core.schema.WorkModel", is_collection=False),
    WizardExportField(path="skills.certifications", python_type="list[str]", is_collection=True),
    WizardExportField(path="skills.languages", python_type="list[str]", is_collection=True),
    WizardExportField(path="skills.must_have", python_type="list[str]", is_collection=True),
    WizardExportField(path="skills.nice_to_have", python_type="list[str]", is_collection=True),
    WizardExportField(path="skills.tools", python_type="list[str]", is_collection=True),
    WizardExportField(path="sources.root", python_type="dict[str, core.schema.SourceAttribution]", is_collection=False),
    WizardExportField(path="summary.culture_highlights", python_type="list[str]", is_collection=True),
    WizardExportField(path="summary.headline", python_type="str | None", is_collection=False),
    WizardExportField(path="summary.next_steps", python_type="list[str]", is_collection=True),
    WizardExportField(path="summary.value_proposition", python_type="str | None", is_collection=False),
    WizardExportField(path="tasks.core", python_type="list[str]", is_collection=True),
    WizardExportField(path="tasks.secondary", python_type="list[str]", is_collection=True),
    WizardExportField(path="tasks.success_metrics", python_type="list[str]", is_collection=True),
    WizardExportField(path="team.collaboration_tools", python_type="str | None", is_collection=False),
    WizardExportField(path="team.headcount_current", python_type="int | None", is_collection=False),
    WizardExportField(path="team.headcount_target", python_type="int | None", is_collection=False),
    WizardExportField(path="team.locations", python_type="str | None", is_collection=False),
    WizardExportField(path="team.mission", python_type="str | None", is_collection=False),
    WizardExportField(path="team.name", python_type="str | None", is_collection=False),
    WizardExportField(path="team.reporting_line", python_type="str | None", is_collection=False),
)

WIZARD_EXPORT_FIELD_TYPES: Final[dict[str, str]] = {
    "benefits.bonus": "str | None",
    "benefits.currency": "str | None",
    "benefits.equity": "str | None",
    "benefits.on_call": "core.schema.OnCallRequirement",
    "benefits.perks": "list[str]",
    "benefits.relocation_support": "str | None",
    "benefits.salary_range": "str | None",
    "benefits.wellbeing": "list[str]",
    "company.benefits": "list[str]",
    "company.brand_color": "str | None",
    "company.brand_keywords": "str | None",
    "company.brand_name": "str | None",
    "company.claim": "str | None",
    "company.contact_email": "pydantic.networks.EmailStr | Literal[''] | None",
    "company.contact_name": "str | None",
    "company.contact_phone": "str | None",
    "company.culture": "str | None",
    "company.description": "str | None",
    "company.hq_location": "str | None",
    "company.industries": "list[str]",
    "company.industry": "str | None",
    "company.legal_name": "str | None",
    "company.locations": "list[str]",
    "company.logo_url": "pydantic.networks.HttpUrl | None",
    "company.mission": "str | None",
    "company.name": "str | None",
    "company.size": "str | None",
    "company.tagline": "str | None",
    "company.values": "list[str]",
    "company.website": "str | None",
    "department.function": "str | None",
    "department.leader_name": "str | None",
    "department.leader_title": "str | None",
    "department.name": "str | None",
    "department.strategic_goals": "str | None",
    "interview_process.decision_timeline": "str | None",
    "interview_process.evaluation_criteria": "list[str]",
    "interview_process.interviewers": "list[str]",
    "interview_process.notes": "str | None",
    "interview_process.steps": "list[str]",
    "missing_fields.root": "dict[str, core.schema.MissingFieldEntry]",
    "position.customer_contact_details": "str | None",
    "position.customer_contact_required": "bool | None",
    "position.reporting_manager_name": "str | None",
    "position.reports_to": "str | None",
    "position.supervises": "int | None",
    "requirements.background_check_required": "bool | None",
    "requirements.portfolio_required": "bool | None",
    "requirements.reference_check_required": "bool | None",
    "role.employment_type": "core.schema.EmploymentType",
    "role.on_call": "core.schema.OnCallRequirement",
    "role.outcomes": "list[str]",
    "role.purpose": "str | None",
    "role.reports_to": "str | None",
    "role.seniority": "str | None",
    "role.title": "str | None",
    "role.work_location": "str | None",
    "role.work_model": "core.schema.WorkModel",
    "skills.certifications": "list[str]",
    "skills.languages": "list[str]",
    "skills.must_have": "list[str]",
    "skills.nice_to_have": "list[str]",
    "skills.tools": "list[str]",
    "sources.root": "dict[str, core.schema.SourceAttribution]",
    "summary.culture_highlights": "list[str]",
    "summary.headline": "str | None",
    "summary.next_steps": "list[str]",
    "summary.value_proposition": "str | None",
    "tasks.core": "list[str]",
    "tasks.secondary": "list[str]",
    "tasks.success_metrics": "list[str]",
    "team.collaboration_tools": "str | None",
    "team.headcount_current": "int | None",
    "team.headcount_target": "int | None",
    "team.locations": "str | None",
    "team.mission": "str | None",
    "team.name": "str | None",
    "team.reporting_line": "str | None",
}

WIZARD_EXPORT_LIST_FIELDS: Final[tuple[str, ...]] = (
    "benefits.perks",
    "benefits.wellbeing",
    "company.benefits",
    "company.industries",
    "company.locations",
    "company.values",
    "interview_process.evaluation_criteria",
    "interview_process.interviewers",
    "interview_process.steps",
    "role.outcomes",
    "skills.certifications",
    "skills.languages",
    "skills.must_have",
    "skills.nice_to_have",
    "skills.tools",
    "summary.culture_highlights",
    "summary.next_steps",
    "tasks.core",
    "tasks.secondary",
    "tasks.success_metrics",
)


def ensure_export_payload(payload: Mapping[str, object] | RecruitingWizard) -> dict[str, object]:
    """Validate ``payload`` against the RecruitingWizard schema and return a JSON payload."""

    export = RecruitingWizardExport.from_payload(payload)
    return export.to_dict()


def iter_export_fields() -> Iterable[WizardExportField]:
    """Yield the canonical export field descriptors."""

    return WIZARD_EXPORT_FIELDS


__all__ = [
    "WizardExportField",
    "WIZARD_EXPORT_FIELDS",
    "WIZARD_EXPORT_FIELD_TYPES",
    "WIZARD_EXPORT_LIST_FIELDS",
    "ensure_export_payload",
    "iter_export_fields",
]
