[theme]
base = "dark"
primaryColor = "#69E2FF"         # cyan accent
backgroundColor = "#0B1220"
secondaryBackgroundColor = "#0F1629"
textColor = "#E6EDF3"
font = "sans serif"

[client]
toolbarMode = "minimal"          # cleaner top-right menu

[browser]
gatherUsageStats = false         # disable telemetry for privacy

[server]
enableCORS = false               # allow cross-origin access (needed for cloud dev environments)
enableXsrfProtection = false     # disable CSRF checks for simpler embedding
