[theme]
base = "dark"
primaryColor = "#DFE3E3"
backgroundColor = "#111414"
secondaryBackgroundColor = "#1A1E1E"
textColor = "#F7F9F9"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "poll"
folderWatchBlacklist = ["^llm/", "^core/", "^components/"]
headless = true
